// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.mvc.react.Component.
*/
goog.provide('este.demos.mvc.react.Component');
goog.require('este.demos.mvc.react.react');
goog.require('este.ui.Component');

/**
  @param {este.demos.mvc.react.Collection} todos
  @constructor
  @extends {este.ui.Component}
*/
este.demos.mvc.react.Component = function(todos) {
  this.todos = todos;
  este.demos.mvc.react.Component.superClass_.constructor.call(this);
}
goog.inherits(este.demos.mvc.react.Component, este.ui.Component);

/**
  @desc este.demos.mvc.react.Component placeholder.
*/
este.demos.mvc.react.Component.MSG_PLACEHOLDER = goog.getMsg('What to do?');

/**
  @desc este.demos.mvc.react.Component add button text.
*/
este.demos.mvc.react.Component.MSG_ADD_BUTTON_LABEL = goog.getMsg('add');

/**
  @type {este.demos.mvc.react.Collection}
  @protected
*/
este.demos.mvc.react.Component.prototype.todos = null;

/**
  @type {React.ReactComponent}
  @protected
*/
este.demos.mvc.react.Component.prototype.react = null;

/**
  @override
*/
este.demos.mvc.react.Component.prototype.createDom = function() {
  este.demos.mvc.react.Component.superClass_.createDom.call(this);
  this.getElement().className = 'todo-mvc-component';
};

/**
  @override
*/
este.demos.mvc.react.Component.prototype.enterDocument = function() {
  este.demos.mvc.react.Component.superClass_.enterDocument.call(this);
  this.update();
  this.on('.new-todo', 'submit', this.onNewTodoSubmit);
  this.on(this.todos, 'update', this.onTodosUpdate);
};

/**
  @protected
*/
este.demos.mvc.react.Component.prototype.onNewTodoSubmit = function(e) {
  var errors, todo;
  todo = new este.demos.mvc.react.Model(e.json);
  errors = todo.validate();
  if (errors) {
    alert(errors[0].getMsg());
    return;
  }
  this.todos.add(todo);
  e.target.reset();
  return this.react.refs['titleInput'].getDOMNode().focus();
};

/**
  @protected
*/
este.demos.mvc.react.Component.prototype.onTodosUpdate = function(e) {
  return this.update();
};

/**
  @protected
*/
este.demos.mvc.react.Component.prototype.update = function() {
  var props;
  props = {
    'todos': this.todos.toJson(),
    'placeholder': este.demos.mvc.react.Component.MSG_PLACEHOLDER,
    'addButtonLabel': este.demos.mvc.react.Component.MSG_ADD_BUTTON_LABEL
  };
  if (!this.react) {
    this.react = este.demos.mvc.react.react(props);
    este.react.render(this.react, this.getElement());
    return;
  }
  return this.react.setProps(props);
};