// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Factory for este.demos.mvc.react.Component.
*/
goog.provide('este.demos.mvc.react.create');
goog.require('este.demos.mvc.react.Collection');
goog.require('este.demos.mvc.react.Component');

/**
  @param {string} selector
  @return {este.demos.mvc.react.Component}
*/
este.demos.mvc.react.create = function(selector) {
  var component, element, todos;
  todos = new este.demos.mvc.react.Collection;
  component = new este.demos.mvc.react.Component(todos);
  element = document.querySelector(selector);
  component.render(element);
  return component;
};