// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.mvc.react.react.
*/
goog.provide('este.demos.mvc.react.react');
goog.require('este.react');
este.demos.mvc.react.react = este.react.create(/** @lends {React.ReactComponent.prototype} */({
  render: function() {
    var _this = this;
    return this.div([
      this.form({
        'className': 'new-todo'
      }, [
        this.input({
          'name': 'title',
          'autoFocus': true,
          'placeholder': this.props['placeholder'],
          'ref': 'titleInput'
        }), this.button(this.props['addButtonLabel'])
      ]), this.ul(this.props['todos'].map(function(todo) {
        return _this.li(todo['title']);
      }))
    ]);
  }
}));