// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.simple.products.list.View.
*/
goog.provide('este.demos.app.simple.products.list.View');
goog.require('este.app.View');
goog.require('este.demos.app.simple.products.list.templates');

/**
  @constructor
  @extends {este.app.View}
*/
este.demos.app.simple.products.list.View = function() {
  este.demos.app.simple.products.list.View.superClass_.constructor.call(this);
}
goog.inherits(este.demos.app.simple.products.list.View, este.app.View);

/**
  @type {este.demos.app.simple.products.Collection}
  @protected
*/
este.demos.app.simple.products.list.View.prototype.products = null;

/**
  @override
*/
este.demos.app.simple.products.list.View.prototype.update = function() {
  var html, links, product;
  window['console']['log']("products rendered");
  links = (function() {
    var _i, _len, _ref, _results;
    _ref = this.products.toJson();
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      product = _ref[_i];
      _results.push({
        name: product['name'],
        description: product['description'],
        href: this.createUrl(este.demos.app.simple.products.detail.Presenter, {
          'id': product['id']
        })
      });
    }
    return _results;
  }).call(this);
  html = este.demos.app.simple.products.list.templates.element({
    links: links,
    timeoutHref: this.createUrl(este.demos.app.simple.timeout.Presenter),
    errorHref: this.createUrl(este.demos.app.simple.error.Presenter)
  });
  this.getElement().innerHTML = html;
};