// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Object utils.
  @namespace este.object
*/
goog.provide('este.object');
goog.require('goog.object');

/**
  If value is array with length == 1, replace array with array[0].
  @param {Object} object
  @return {Object}
*/
este.object.normalizeOneItemArrayValues = function(object) {
  var key, normalized, value;
  normalized = {};
  for (key in object) {
    value = object[key];
    if (goog.isArray(value) && value.length === 1) {
      normalized[key] = value[0];
      continue;
    }
    normalized[key] = value;
  }
  return normalized;
};