// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.object', function() {
  var object;
  object = este.object;
  return suite('normalizeOneItemArrayValues', function() {
    return test('should sd', function() {
      var result;
      result = object.normalizeOneItemArrayValues({
        'a': 1,
        'b': [1],
        'c': [1, 2]
      });
      return assert.deepEqual(result, {
        'a': 1,
        'b': 1,
        'c': [1, 2]
      });
    });
  });
});