// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Simple LightBox.

  @see /demos/ui/lightbox.html
*/
goog.provide('este.ui.lightbox.create');
goog.require('este.ui.lightbox.Lightbox');
goog.require('este.ui.lightbox.View');

/**
  @param {{
    element: (Element|undefined)
  }=} options
*/
este.ui.lightbox.create = function(options) {
  var createView, lightbox;
  createView = function(anchor, anchors) {
    return new este.ui.lightbox.View(anchor, anchors);
  };
  lightbox = new este.ui.lightbox.Lightbox(createView);
  lightbox.decorate((options != null ? options.element : void 0) || document.body);
  return lightbox;
};