// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.ui.lightbox.View.
*/
goog.provide('este.ui.lightbox.View');
goog.provide('este.ui.lightbox.View.EventType');
goog.require('este.ui.Component');
goog.require('este.ui.lightbox.templates');

/**
  @param {Element} currentAnchor
  @param {Array.<Element>} anchors
  @constructor
  @extends {este.ui.Component}
*/
este.ui.lightbox.View = function(currentAnchor, anchors) {
  this.currentAnchor = currentAnchor;
  this.anchors = anchors;
  este.ui.lightbox.View.superClass_.constructor.call(this);
}
goog.inherits(este.ui.lightbox.View, este.ui.Component);

/**
  @enum {string}
*/
este.ui.lightbox.View.EventType = {
  CLOSE: 'close'
};

/**
  @type {string}
*/
este.ui.lightbox.View.prototype.className = 'e-ui-lightbox';

/**
  @type {Element}
  @protected
*/
este.ui.lightbox.View.prototype.currentAnchor = null;

/**
  @type {Array.<Element>}
  @protected
*/
este.ui.lightbox.View.prototype.anchors = null;

/**
  @override
*/
este.ui.lightbox.View.prototype.createDom = function() {
  este.ui.lightbox.View.superClass_.createDom.call(this);
  this.getElement().className = this.className;
  goog.dom.setFocusableTabIndex(this.getElement(), true);
  this.update();
  este.dom.focusAsync(this.getElement());
};

/**
  @override
*/
este.ui.lightbox.View.prototype.canDecorate = function(element) {
  return false;
};

/**
  @override
*/
este.ui.lightbox.View.prototype.enterDocument = function() {
  este.ui.lightbox.View.superClass_.enterDocument.call(this);
  this.on('.e-ui-lightbox-close', 'click', this.close);
  this.on('.e-ui-lightbox-previous', 'click', this.moveLeft);
  this.on('.e-ui-lightbox-next', 'click', this.moveRight);
  this.on('*', goog.events.KeyCodes.ESC, this.close);
  this.on('*', [goog.events.KeyCodes.LEFT, goog.events.KeyCodes.UP], this.moveLeft);
  this.on('*', [goog.events.KeyCodes.RIGHT, goog.events.KeyCodes.DOWN], this.moveRight);
  this.on('*', [goog.events.KeyCodes.HOME, goog.events.KeyCodes.PAGE_UP], this.moveStart);
  this.on('*', [goog.events.KeyCodes.END, goog.events.KeyCodes.PAGE_DOWN], this.moveEnd);
};

/**
  @protected
*/
este.ui.lightbox.View.prototype.close = function() {
  return this.dispatchEvent(este.ui.lightbox.View.EventType.CLOSE);
};

/**
  @protected
*/
este.ui.lightbox.View.prototype.moveLeft = function() {
  this.move(false);
  return this.update();
};

/**
  @protected
*/
este.ui.lightbox.View.prototype.moveRight = function() {
  this.move(true);
  return this.update();
};

/**
  @protected
*/
este.ui.lightbox.View.prototype.moveStart = function() {
  this.currentAnchor = this.anchors[0];
  return this.update();
};

/**
  @protected
*/
este.ui.lightbox.View.prototype.moveEnd = function() {
  this.currentAnchor = this.anchors[this.anchors.length - 1];
  return this.update();
};

/**
  @param {boolean} next
  @protected
*/
este.ui.lightbox.View.prototype.move = function(next) {
  var anchor, idx;
  idx = goog.array.indexOf(this.anchors, this.currentAnchor);
  if (next) {
    idx++;
  } else {
    idx--;
  }
  anchor = this.anchors[idx];
  if (!anchor) {
    return;
  }
  return this.currentAnchor = anchor;
};

/**
  @protected
*/
este.ui.lightbox.View.prototype.update = function() {
  var html, json;
  json = this.getViewJson();
  html = este.ui.lightbox.templates.view(json);
  return this.getElement().innerHTML = html;
};

/**
  @return {Object}
  @protected
*/
este.ui.lightbox.View.prototype.getViewJson = function() {
  return {
    src: this.currentAnchor.href,
    title: this.currentAnchor.title,
    idx: goog.array.indexOf(this.anchors, this.currentAnchor),
    total: this.anchors.length
  };
};