// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.layout.layouts.sidebar.View.
*/
goog.provide('este.demos.app.layout.layouts.sidebar.View');
goog.require('este.demos.app.layout.layouts.master.View');
goog.require('este.demos.app.layout.foo.View');
goog.require('este.demos.app.layout.bla.View');

/**
  @param {Object.<string, este.app.View>} views
  @constructor
  @extends {este.demos.app.layout.layouts.master.View}
*/
este.demos.app.layout.layouts.sidebar.View = function(views) {
  este.demos.app.layout.layouts.sidebar.View.superClass_.constructor.call(this, views);
}
goog.inherits(este.demos.app.layout.layouts.sidebar.View, este.demos.app.layout.layouts.master.View);

/**
  @override
*/
este.demos.app.layout.layouts.sidebar.View.prototype.renderSidebar = function(el) {
  return el.innerHTML = este.app.renderLinks(this, [
    {
      title: 'Foo',
      presenter: este.demos.app.layout.foo.Presenter,
      selected: this.content instanceof este.demos.app.layout.foo.View
    }, {
      title: 'Bla',
      presenter: este.demos.app.layout.bla.Presenter,
      selected: this.content instanceof este.demos.app.layout.bla.View
    }
  ]);
};