// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.simple.timeout.Presenter.
*/
goog.provide('este.demos.app.simple.timeout.Presenter');
goog.require('este.app.Presenter');

/**
  @constructor
  @extends {este.app.Presenter}
*/
este.demos.app.simple.timeout.Presenter = function() {
  este.demos.app.simple.timeout.Presenter.superClass_.constructor.call(this);
}
goog.inherits(este.demos.app.simple.timeout.Presenter, este.app.Presenter);

/**
  @override
*/
este.demos.app.simple.timeout.Presenter.prototype.load = function(params) {
  var result;
  result = new goog.result.SimpleResult;
  setTimeout(function() {
    return result.setValue(null);
  }, 12000);
  return result;
};