// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.app.Route', function() {
  var Route, route;
  Route = este.app.Route;
  route = null;
  setup(function() {
    return route = new Route;
  });
  return suite('constructor', function() {
    test('should work', function() {
      return assert.instanceOf(route, Route);
    });
    return test('should set path and presenter', function() {
      var presenter;
      presenter = {};
      route = new Route('a', presenter);
      assert.equal(route.path, 'a');
      return assert.equal(route.presenter, presenter);
    });
  });
});