// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.app.Request.
*/
goog.provide('este.app.Request');
goog.require('este.json');

/**
  @param {este.app.Presenter} presenter
  @param {Object=} params
  @param {boolean=} isNavigation True if request is dispatched as result of
      back forward browser button. If so, the url is yet changed.
  @constructor
*/
este.app.Request = function(presenter, params, isNavigation) {
  this.presenter = presenter;
  this.params = params != null ? params : null;
  this.isNavigation = isNavigation != null ? isNavigation : false;
}

/**
  @type {este.app.Presenter}
*/
este.app.Request.prototype.presenter = null;

/**
  @type {Object}
*/
este.app.Request.prototype.params = null;

/**
  @type {boolean}
*/
este.app.Request.prototype.isNavigation = false;

/**
  @param {este.app.Request} req
*/
este.app.Request.prototype.equal = function(req) {
  return this.presenter === req.presenter && este.json.equal(this.params, req.params);
};