// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.app.Request', function() {
  var Request, params, presenter, request;
  Request = este.app.Request;
  presenter = null;
  params = null;
  request = null;
  setup(function() {
    presenter = {};
    params = {
      1: 'foo'
    };
    return request = new Request(presenter, params);
  });
  suite('constructor', function() {
    return test('should work', function() {
      return assert.instanceOf(request, Request);
    });
  });
  return suite('equal', function() {
    test('should equal same presenter and params', function() {
      var sameRequest;
      sameRequest = new Request(presenter, params);
      return assert.isTrue(request.equal(sameRequest));
    });
    test('should equal same presenter without params', function() {
      var sameRequest;
      request = new Request(presenter);
      sameRequest = new Request(presenter);
      return assert.isTrue(request.equal(sameRequest));
    });
    test('should not equal same presenter and different params', function() {
      var differentRequest;
      differentRequest = new Request(presenter, {
        2: 'bla'
      });
      return assert.isFalse(request.equal(differentRequest));
    });
    return test('should not equal different presenter and same params', function() {
      var differentRequest;
      differentRequest = new Request({}, params);
      return assert.isFalse(request.equal(differentRequest));
    });
  });
});