// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Collection representing list of todos models.
*/
goog.provide('este.demos.mvc.closureTemplates.Collection');
goog.require('este.demos.mvc.closureTemplates.Model');
goog.require('este.Collection');

/**
  @param {Array=} array We can fulfil collection with plain array of JSONs.
  @constructor
  @extends {este.Collection}
*/
este.demos.mvc.closureTemplates.Collection = function(array) {
  este.demos.mvc.closureTemplates.Collection.superClass_.constructor.call(this, array);
}
goog.inherits(este.demos.mvc.closureTemplates.Collection, este.Collection);

/**
  @override
*/
este.demos.mvc.closureTemplates.Collection.prototype.model = este.demos.mvc.closureTemplates.Model;