// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.mvc.closureTemplates.Component.
*/
goog.provide('este.demos.mvc.closureTemplates.Component');
goog.require('este.demos.mvc.closureTemplates.templates');
goog.require('este.ui.Component');

/**
  @param {este.demos.mvc.closureTemplates.Collection} todos
  @constructor
  @extends {este.ui.Component}
*/
este.demos.mvc.closureTemplates.Component = function(todos) {
  this.todos = todos;
  este.demos.mvc.closureTemplates.Component.superClass_.constructor.call(this);
}
goog.inherits(este.demos.mvc.closureTemplates.Component, este.ui.Component);

/**
  @type {este.demos.mvc.closureTemplates.Collection}
  @protected
*/
este.demos.mvc.closureTemplates.Component.prototype.todos = null;

/**
  @override
*/
este.demos.mvc.closureTemplates.Component.prototype.createDom = function() {
  este.demos.mvc.closureTemplates.Component.superClass_.createDom.call(this);
  this.getElement().className = 'todo-mvc-component';
};

/**
  @override
*/
este.demos.mvc.closureTemplates.Component.prototype.enterDocument = function() {
  este.demos.mvc.closureTemplates.Component.superClass_.enterDocument.call(this);
  this.update();
  this.on('.new-todo', 'submit', this.onNewTodoSubmit);
  this.on(this.todos, 'update', this.onTodosUpdate);
};

/**
  @param {este.events.SubmitEvent} e
  @protected
*/
este.demos.mvc.closureTemplates.Component.prototype.onNewTodoSubmit = function(e) {
  var errors, todo;
  todo = new este.demos.mvc.closureTemplates.Model(e.json);
  errors = todo.validate();
  if (errors) {
    alert(errors[0].getMsg());
    return;
  }
  this.todos.add(todo);
  return e.target.reset();
};

/**
  @protected
*/
este.demos.mvc.closureTemplates.Component.prototype.onTodosUpdate = function(e) {
  return this.update();
};

/**
  @protected
*/
este.demos.mvc.closureTemplates.Component.prototype.update = function() {
  var html;
  html = este.demos.mvc.closureTemplates.templates.element({
    todos: this.todos.toJson()
  });
  return this.getElement().innerHTML = html;
};