// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.layout.contacts.Presenter.
*/
goog.provide('este.demos.app.layout.contacts.Presenter');
goog.require('este.app.Presenter');
goog.require('este.demos.app.layout.contacts.View');
goog.require('este.demos.app.layout.layouts.master.View');

/**
  @constructor
  @extends {este.app.Presenter}
*/
este.demos.app.layout.contacts.Presenter = function() {
  este.demos.app.layout.contacts.Presenter.superClass_.constructor.call(this);
  this.view = new este.demos.app.layout.layouts.master.View({
    content: new este.demos.app.layout.contacts.View
  });
}
goog.inherits(este.demos.app.layout.contacts.Presenter, este.app.Presenter);