// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.layout.contacts.View.
*/
goog.provide('este.demos.app.layout.contacts.View');
goog.require('este.app.View');

/**
  @constructor
  @extends {este.app.View}
*/
este.demos.app.layout.contacts.View = function() {
  este.demos.app.layout.contacts.View.superClass_.constructor.call(this);
}
goog.inherits(este.demos.app.layout.contacts.View, este.app.View);

/**
  @override
*/
este.demos.app.layout.contacts.View.prototype.update = function() {
  this.getElement().innerHTML = 'Contacts content.';
};