// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Render links via soy templates to have content contextually
  autoescaped to eliminate the risk of XSS.
*/
goog.provide('este.app.renderLinks');
goog.require('este.app.renderlinks.templates');

/**
  @param {este.app.View} view
  @param {Array.<Object>} links
  @return {string}
*/
este.app.renderLinks = function(view, links) {
  var json, link;
  json = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = links.length; _i < _len; _i++) {
      link = links[_i];
      _results.push({
        title: link.title,
        selected: link.selected,
        href: view.createUrl(link.presenter)
      });
    }
    return _results;
  })();
  return este.app.renderlinks.templates.links({
    links: json
  });
};