// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.demos.app.todomvc.todos.Model', function() {
  var Model, model;
  Model = este.demos.app.todomvc.todos.Model;
  model = null;
  setup(function() {
    return model = new Model;
  });
  suite('constructor', function() {
    test('should work', function() {
      return assert.instanceOf(model, Model);
    });
    return test('should set default value', function() {
      var json;
      json = model.toJson(true);
      return assert.deepEqual(json, {
        title: '',
        completed: false,
        editing: false
      });
    });
  });
  suite('set title', function() {
    return test('should be trimmed', function() {
      model.set('title', '  foo  ');
      return assert.equal(model.get('title'), 'foo');
    });
  });
  suite('validate', function() {
    return test('should return Required validator', function() {
      var errors;
      errors = model.validate();
      assert.isArray(errors);
      assert.lengthOf(errors, 1);
      assert.equal(errors[0].model, model);
      assert.equal(errors[0].key, 'title');
      return assert.equal(errors[0].value, '');
    });
  });
  return suite('toggleCompleted', function() {
    return test('should toggle completed', function() {
      assert.isFalse(model.get('completed'));
      model.toggleCompleted();
      assert.isTrue(model.get('completed'));
      model.toggleCompleted();
      return assert.isFalse(model.get('completed'));
    });
  });
});