// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Model representing one todo.
*/
goog.provide('este.demos.app.todomvc.todos.Model');
goog.require('este.Model');

/**
  @param {Object=} json
  @constructor
  @extends {este.Model}
*/
este.demos.app.todomvc.todos.Model = function(json) {
  este.demos.app.todomvc.todos.Model.superClass_.constructor.call(this, json);
}
goog.inherits(este.demos.app.todomvc.todos.Model, este.Model);

/**
  @override
*/
este.demos.app.todomvc.todos.Model.prototype.url = '/todos';

/**
  @override
*/
este.demos.app.todomvc.todos.Model.prototype.defaults = {
  'title': '',
  'completed': false,
  'editing': false
};

/**
  @override
*/
este.demos.app.todomvc.todos.Model.prototype.schema = {
  'title': {
    'set': este.model.setters.trim,
    'validators': [este.validators.required()]
  }
};
este.demos.app.todomvc.todos.Model.prototype.toggleCompleted = function() {
  return this.set('completed', !this.get('completed'));
};