// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.storage.Base', function() {
  var Base, base, collection, params;
  Base = este.storage.Base;
  collection = null;
  params = {};
  base = null;
  setup(function() {
    collection = {};
    params = {};
    return base = new Base;
  });
  return suite('query', function() {
    return test('should accept optional url', function(done) {
      base.queryInternal = function(p_collection, p_url, p_params) {
        assert.equal(p_collection, collection);
        assert.equal(p_url, 'url');
        assert.equal(p_params, params);
        return done();
      };
      return base.query(collection, params, 'url');
    });
  });
});