// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.storage.Rest', function() {
  var Rest, namespace, rest;
  Rest = este.storage.Rest;
  rest = null;
  namespace = null;
  setup(function() {
    namespace = 'foo';
    return rest = new Rest(namespace);
  });
  suite('constructor', function() {
    test('should work', function() {
      return assert.instanceOf(rest, Rest);
    });
    return test('should replace version parametr in namespace', function() {
      namespace = 'https://api.mongolab.com/api/:version/databases';
      rest = new Rest(namespace, 1);
      return assert.equal(rest.namespace, 'https://api.mongolab.com/api/1/databases');
    });
  });
  return suite('getRestUrl', function() {
    test('should append url', function() {
      var url;
      url = rest.getRestUrl('bla');
      return assert.equal(url, 'foo/bla');
    });
    test('should append id', function() {
      var url;
      url = rest.getRestUrl('bla', '1');
      return assert.equal(url, 'foo/bla/1');
    });
    test('should not append id', function() {
      var url;
      url = rest.getRestUrl('bla', '');
      return assert.equal(url, 'foo/bla');
    });
    return test('should not append id but should append query params', function() {
      var url;
      rest = new Rest(namespace, 1, {
        'foo': 'bla'
      });
      url = rest.getRestUrl('bla', '');
      return assert.equal(url, 'foo/bla?foo=bla');
    });
  });
});