// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Getters for este.Model
  @namespace este.model.getters
*/
goog.provide('este.model.getters');
goog.require('goog.string');

/**
  @param {string} value
  @return {number}
*/
este.model.getters.parseInt = function(value) {
  return parseInt(value, 10);
};