// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Setters for este.Model
  @namespace este.model.setters
*/
goog.provide('este.model.setters');
goog.require('goog.string');

/**
  @param {string} value
  @return {string}
*/
este.model.setters.trim = function(value) {
  return goog.string.trim(value);
};