// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.simple.products.Collection.
*/
goog.provide('este.demos.app.simple.products.Collection');
goog.require('este.Collection');
goog.require('este.demos.app.simple.products.Model');

/**
  @param {Array=} array
  @constructor
  @extends {este.Collection}
*/
este.demos.app.simple.products.Collection = function(array) {
  este.demos.app.simple.products.Collection.superClass_.constructor.call(this, array);
}
goog.inherits(este.demos.app.simple.products.Collection, este.Collection);

/**
  @override
*/
este.demos.app.simple.products.Collection.prototype.model = este.demos.app.simple.products.Model;