// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.simple.products.Model.
*/
goog.provide('este.demos.app.simple.products.Model');
goog.require('este.Model');

/**
  @param {Object=} json
  @constructor
  @extends {este.Model}
*/
este.demos.app.simple.products.Model = function(json) {
  este.demos.app.simple.products.Model.superClass_.constructor.call(this, json);
}
goog.inherits(este.demos.app.simple.products.Model, este.Model);

/**
  @override
*/
este.demos.app.simple.products.Model.prototype.schema = {
  'name': {
    'set': este.model.setters.trim,
    'validators': [este.validators.required()]
  },
  'description': {
    'set': este.model.setters.trim,
    'validators': [este.validators.required()]
  }
};