// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.validators.Base', function() {
  var Base, base;
  Base = este.validators.Base;
  base = null;
  setup(function() {
    return base = new Base;
  });
  suite('constructor', function() {
    return test('should work', function() {
      return assert.instanceOf(base, Base);
    });
  });
  return suite('isValidable', function() {
    test('should return true for validable values', function() {
      base.value = ' ';
      assert.isTrue(base.isValidable());
      base.value = 0;
      assert.isTrue(base.isValidable());
      base.value = '123';
      assert.isTrue(base.isValidable());
      base.value = {};
      return assert.isTrue(base.isValidable());
    });
    return test('should return false for invalidable values', function() {
      base.value = '';
      assert.isFalse(base.isValidable());
      base.value = null;
      assert.isFalse(base.isValidable());
      base.value = void 0;
      return assert.isFalse(base.isValidable());
    });
  });
});