// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.validators.digits', function() {
  var digits;
  digits = null;
  setup(function() {
    return digits = este.validators.digits()();
  });
  suite('validate', function() {
    suite('should be valid:', function() {
      return test('123', function() {
        digits.value = '123';
        return assert.isTrue(digits.validate());
      });
    });
    return suite('should be invalid:', function() {
      test('""', function() {
        digits.value = '';
        return assert.isFalse(digits.validate());
      });
      test('123.3', function() {
        digits.value = '123.3';
        return assert.isFalse(digits.validate());
      });
      test('"1e1" (scientific notation)', function() {
        digits.value = '1e1';
        return assert.isFalse(digits.validate());
      });
      test('foo', function() {
        digits.value = 'foo';
        return assert.isFalse(digits.validate());
      });
      return test('" "', function() {
        digits.value = ' ';
        return assert.isFalse(digits.validate());
      });
    });
  });
  return suite('getMsg', function() {
    test('should return message', function() {
      return assert.equal(digits.getMsg(), 'Please enter only digits.');
    });
    return test('should return alternative message', function() {
      var getMsg;
      getMsg = function() {
        return 'This is not digits.';
      };
      digits = este.validators.digits(getMsg)();
      return assert.equal(digits.getMsg(), getMsg());
    });
  });
});