// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Validate string with regex.
*/
goog.provide('este.validators.Format');
goog.provide('este.validators.format');
goog.require('este.validators.Base');

/**
  @param {RegExp} regexp
  @param {function(): string=} getMsg
  @constructor
  @extends {este.validators.Base}
*/
este.validators.Format = function(regexp, getMsg) {
  this.regexp = regexp;
  este.validators.Format.superClass_.constructor.call(this, getMsg);
}
goog.inherits(este.validators.Format, este.validators.Base);

/**
  @type {RegExp}
  @protected
*/
este.validators.Format.prototype.regexp = null;

/**
  @override
*/
este.validators.Format.prototype.validate = function() {
  goog.asserts.assertString(this.value);
  return this.regexp.test(this.value);
};

/**
  @override
*/
este.validators.Format.prototype.getMsg = function() {
  
/**
    @desc Format validator message.
  */
  return este.validators.Format.MSG_VALIDATOR_FORMAT = goog.getMsg('Please enter a value in correct format.');
};

/**
  @param {RegExp} regexp
  @param {function(): string=} getMsg
  @return {function(): este.validators.Format}
*/
este.validators.format = function(regexp, getMsg) {
  return function() {
    return new este.validators.Format(regexp, getMsg);
  };
};