// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Validate number or string number.
*/
goog.provide('este.validators.Min');
goog.provide('este.validators.min');
goog.require('este.validators.Base');
goog.require('goog.math');
goog.require('goog.string');

/**
  @param {number} min
  @param {function(): string=} getMsg
  @constructor
  @extends {este.validators.Base}
*/
este.validators.Min = function(min, getMsg) {
  this.min = min;
  este.validators.Min.superClass_.constructor.call(this, getMsg);
}
goog.inherits(este.validators.Min, este.validators.Base);

/**
  @type {number}
  @protected
*/
este.validators.Min.prototype.min = 0;

/**
  @override
*/
este.validators.Min.prototype.validate = function() {
  var isStringOrNumber, value, _ref;
  isStringOrNumber = (_ref = typeof this.value) === 'string' || _ref === 'number';
  goog.asserts.assert(isStringOrNumber, 'Expected string or number.');
  value = this.value;
  if (goog.isString(value)) {
    value = goog.string.toNumber(value);
  }
  value = /** @type {number} */(value);
  if (!goog.math.isFiniteNumber(value)) {
    return false;
  }
  return value >= this.min;
};

/**
  @override
*/
este.validators.Min.prototype.getMsg = function() {
  
/**
    @desc Min validator message.
  */
  return este.validators.Min.MSG_VALIDATOR_MIN = goog.getMsg('Please enter a value greater than or equal to {$min}.', {
    'min': this.min
  });
};

/**
  @param {number} min
  @param {function(): string=} getMsg
  @return {function(): este.validators.Min}
*/
este.validators.min = function(min, getMsg) {
  return function() {
    return new este.validators.Min(min, getMsg);
  };
};