// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.validators.number', function() {
  var number;
  number = null;
  setup(function() {
    return number = este.validators.number()();
  });
  suite('validate', function() {
    suite('should be valid:', function() {
      test('123', function() {
        number.value = '123';
        return assert.isTrue(number.validate());
      });
      test('123.3', function() {
        number.value = '123.3';
        return assert.isTrue(number.validate());
      });
      return test('"1e1" (scientific notation)', function() {
        number.value = '1e1';
        return assert.isTrue(number.validate());
      });
    });
    return suite('should be invalid:', function() {
      return test('foo should be invalid', function() {
        number.value = 'foo';
        return assert.isFalse(number.validate());
      });
    });
  });
  return suite('getMsg', function() {
    test('should return message', function() {
      return assert.equal(number.getMsg(), 'Please enter a valid number.');
    });
    return test('should return alternative message', function() {
      var getMsg;
      getMsg = function() {
        return 'This is not number.';
      };
      number = este.validators.number(getMsg)();
      return assert.equal(number.getMsg(), getMsg());
    });
  });
});