// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Align one element with anoter element via CSS3 animations.
  TODO: consider better names then linksContainer, targetsContainer
*/
goog.provide('este.labs.ui.Baseliner');
goog.require('este.thirdParty.pointerEvents');
goog.require('goog.dom.classlist');
goog.require('goog.style');
goog.require('goog.ui.Component');

/**
  @param {Element} linksContainer
  @param {Element} targetsContainer
  @constructor
  @extends {goog.ui.Component}
*/
este.labs.ui.Baseliner = function(linksContainer, targetsContainer) {
  this.linksContainer = linksContainer;
  this.targetsContainer = targetsContainer;
  este.labs.ui.Baseliner.superClass_.constructor.call(this);
  este.thirdParty.pointerEvents.install();
}
goog.inherits(este.labs.ui.Baseliner, goog.ui.Component);

/**
  @type {string}
*/
este.labs.ui.Baseliner.prototype.selectedClassName = 'selected';

/**
  @type {Element}
  @protected
*/
este.labs.ui.Baseliner.prototype.linksContainer = null;

/**
  @type {Element}
  @protected
*/
este.labs.ui.Baseliner.prototype.targetsContainer = null;

/**
  @type {number}
  @protected
*/
este.labs.ui.Baseliner.prototype.prevY = 0;

/**
  @type {Element}
  @protected
*/
este.labs.ui.Baseliner.prototype.prevSelectedLink = null;

/**
  @type {Element}
  @protected
*/
este.labs.ui.Baseliner.prototype.prevSelectedTarget = null;

/**
  @override
*/
este.labs.ui.Baseliner.prototype.enterDocument = function() {
  var eventType;
  este.labs.ui.Baseliner.superClass_.enterDocument.call(this);
  eventType = este.thirdParty.pointerEvents.isSupported() ? goog.events.EventType.POINTERUP : goog.events.EventType.MOUSEDOWN;
  this.getHandler().listen(this.linksContainer, eventType, this.onLinksContainerPointerUp);
};

/**
  @param {goog.events.BrowserEvent} e
  @protected
*/
este.labs.ui.Baseliner.prototype.onLinksContainerPointerUp = function(e) {
  var link;
  link = e.target;
  if (link.parentNode !== this.linksContainer) {
    return;
  }
  return this.alignLinkWithItsTarget(link);
};

/**
  @param {Node} link
  @protected
*/
este.labs.ui.Baseliner.prototype.alignLinkWithItsTarget = function(link) {
  var target;
  target = this.targetsContainer.children[this.getLinkIndex(link)];
  this.prevY = this.getLinkAndTargetDiff(link, target) + this.prevY;
  if (!this.prevY) {
    return;
  }
  goog.style.setStyle(this.targetsContainer, {
    'transition': '-webkit-transform .3s ease-in-out',
    'transform': "translateY(" + this.prevY + "px)"
  });
  return this.setSelectedClasses(link, target);
};

/**
  @param {Node} link
  @return {number}
  @protected
*/
este.labs.ui.Baseliner.prototype.getLinkIndex = function(link) {
  return goog.array.toArray(this.linksContainer.children).indexOf(link);
};

/**
  @param {Node} link
  @param {Node} target
  @return {number}
  @protected
*/
este.labs.ui.Baseliner.prototype.getLinkAndTargetDiff = function(link, target) {
  return Math.round(link.getBoundingClientRect().top - Math.round(target.getBoundingClientRect().top));
};

/**
  @param {Node} link
  @param {Node} target
  @protected
*/
este.labs.ui.Baseliner.prototype.setSelectedClasses = function(link, target) {
  if (this.prevSelectedLink) {
    goog.dom.classlist.remove(this.prevSelectedLink, this.selectedClassName);
  }
  if (this.prevSelectedTarget) {
    goog.dom.classlist.remove(this.prevSelectedTarget, this.selectedClassName);
  }
  this.prevSelectedLink = /** @type {Element} */(link);
  this.prevSelectedTarget = /** @type {Element} */(target);
  goog.dom.classlist.add(this.prevSelectedLink, this.selectedClassName);
  return goog.dom.classlist.add(this.prevSelectedTarget, this.selectedClassName);
};