// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.simple.products.detail.Presenter.
*/
goog.provide('este.demos.app.simple.products.detail.Presenter');
goog.require('este.app.Presenter');
goog.require('este.demos.app.simple.products.detail.View');

/**
  @constructor
  @extends {este.app.Presenter}
*/
este.demos.app.simple.products.detail.Presenter = function() {
  este.demos.app.simple.products.detail.Presenter.superClass_.constructor.call(this);
  this.view = new este.demos.app.simple.products.detail.View;
}
goog.inherits(este.demos.app.simple.products.detail.Presenter, este.app.Presenter);

/**
  @override
*/
este.demos.app.simple.products.detail.Presenter.prototype.load = function(params) {
  var delay, result;
  if (params == null) {
    params = {};
  }
  window['console']['log']('loading product/' + params['id']);
  delay = 2000;
  if (params['id'] === '0') {
    delay = 6000;
  }
  result = new goog.result.SimpleResult;
  setTimeout(function() {
    return result.setValue(params);
  }, delay);
  return result;
};

/**
  @override
*/
este.demos.app.simple.products.detail.Presenter.prototype.show = function(result) {
  this.view.params = /** @type {Object} */(result.getValue());
};