// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.simple.products.detail.View.
*/
goog.provide('este.demos.app.simple.products.detail.View');
goog.require('este.app.View');
goog.require('este.demos.app.simple.products.detail.templates');

/**
  @constructor
  @extends {este.app.View}
*/
este.demos.app.simple.products.detail.View = function() {
  este.demos.app.simple.products.detail.View.superClass_.constructor.call(this);
}
goog.inherits(este.demos.app.simple.products.detail.View, este.app.View);

/**
  @type {Object}
  @protected
*/
este.demos.app.simple.products.detail.View.prototype.params = null;

/**
  @override
*/
este.demos.app.simple.products.detail.View.prototype.enterDocument = function() {
  este.demos.app.simple.products.detail.View.superClass_.enterDocument.call(this);
  this.on('button', 'click', this.onButtonClick);
};

/**
  @param {goog.events.BrowserEvent} e
  @protected
*/
este.demos.app.simple.products.detail.View.prototype.onButtonClick = function(e) {
  return this.redirect(este.demos.app.simple.products.list.Presenter);
};

/**
  @override
*/
este.demos.app.simple.products.detail.View.prototype.update = function() {
  var html;
  window['console']['log']("product with id " + this.params['id'] + " rendered");
  html = este.demos.app.simple.products.detail.templates.element({
    id: this.params['id']
  });
  this.getElement().innerHTML = html;
};