// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview View for list of todos.
*/
goog.provide('este.demos.app.todomvc.todos.list.View');
goog.require('este.app.View');
goog.require('este.demos.app.todomvc.todos.list.react');
goog.require('goog.i18n.pluralRules');

/**
  @constructor
  @extends {este.app.View}
*/
este.demos.app.todomvc.todos.list.View = function() {
  este.demos.app.todomvc.todos.list.View.superClass_.constructor.call(this);
}
goog.inherits(este.demos.app.todomvc.todos.list.View, este.app.View);

/**
  @type {este.demos.app.todomvc.todos.Collection}
*/
este.demos.app.todomvc.todos.list.View.prototype.todos = null;

/**
  @type {React.ReactComponent}
  @protected
*/
este.demos.app.todomvc.todos.list.View.prototype.react = null;

/**
  @override
*/
este.demos.app.todomvc.todos.list.View.prototype.enterDocument = function() {
  este.demos.app.todomvc.todos.list.View.superClass_.enterDocument.call(this);
  this.on('.new-todo-form', 'submit', this.onNewTodoSubmit);
  this.on('.toggle-all', 'click', this.onToggleAllClick);
  this.on('.clear-completed', 'click', this.onClearCompletedClick);
  this.on('.toggle', 'click', this.bindModel(this.onToggleClick));
  this.on('.destroy', 'click', this.bindModel(this.onDestroyClick));
  this.on('label', 'dblclick', this.bindModel(this.onLabelDblclick));
  this.on('.edit', ['focusout', goog.events.KeyCodes.ENTER], this.bindModel(this.onEditEnd));
};

/**
  @param {este.events.SubmitEvent} e
  @protected
*/
este.demos.app.todomvc.todos.list.View.prototype.onNewTodoSubmit = function(e) {
  var errors, todo;
  todo = new este.demos.app.todomvc.todos.Model(e.json);
  errors = todo.validate();
  if (errors) {
    return;
  }
  e.target.elements['title'].value = '';
  return this.todos.add(todo);
};

/**
  @protected
*/
este.demos.app.todomvc.todos.list.View.prototype.onToggleAllClick = function() {
  return this.todos.toggleAll();
};

/**
  @protected
*/
este.demos.app.todomvc.todos.list.View.prototype.onClearCompletedClick = function() {
  return this.todos.clearCompleted();
};

/**
  @param {este.demos.app.todomvc.todos.Model} model
  @protected
*/
este.demos.app.todomvc.todos.list.View.prototype.onToggleClick = function(model) {
  return model.toggleCompleted();
};

/**
  @param {este.demos.app.todomvc.todos.Model} model
  @protected
*/
este.demos.app.todomvc.todos.list.View.prototype.onDestroyClick = function(model) {
  return this.todos.remove(model);
};

/**
  @param {este.demos.app.todomvc.todos.Model} model
  @param {Element} el
  @protected
*/
este.demos.app.todomvc.todos.list.View.prototype.onLabelDblclick = function(model, el) {
  var edit;
  model.set('editing', true);
  edit = el.querySelector('.edit');
  return este.dom.focusAsync(edit);
};

/**
  @param {este.demos.app.todomvc.todos.Model} model
  @param {Element} el
  @protected
*/
este.demos.app.todomvc.todos.list.View.prototype.onEditEnd = function(model, el) {
  var edit, title;
  edit = el.querySelector('.edit');
  title = goog.string.trim(edit.value);
  if (!title) {
    this.todos.remove(model);
    return;
  }
  return model.set({
    'title': title,
    'editing': false
  });
};

/**
  This method is called when view is shown and when todos collection is
  changed.
  @override
*/
este.demos.app.todomvc.todos.list.View.prototype.update = function() {
  var length, props, remainingCount;
  length = this.todos.getLength();
  remainingCount = this.todos.getRemainingCount();
  props = {
    'doneCount': length - remainingCount,
    'itemsLeftLocalized': this.getItemsLeftLocalized(remainingCount),
    'remainingCount': remainingCount,
    'showBodyAndFooter': length > 0,
    'state': this.todos.state || '',
    'todos': this.todos.filterByState()
  };
  if (!this.react) {
    this.react = este.demos.app.todomvc.todos.list.react(props);
    este.react.render(this.react, this.getElement());
    return;
  }
  return this.react.setProps(props);
};

/**
  This method allows us to define plural translations for every language.
  @param {number} remainingCount
  @return {string} Localized string.
  @protected
  @see estejs.tumblr.com/post/35639619128/este-js-localization-cheat-sheet
*/
este.demos.app.todomvc.todos.list.View.prototype.getItemsLeftLocalized = function(remainingCount) {
  switch (goog.i18n.pluralRules.select(remainingCount)) {
    case goog.i18n.pluralRules.Keyword.ZERO:
      
/**
        @desc Zero items left.
        @protected
      */
      return este.demos.app.todomvc.todos.list.View.MSG_ZERO_ITEMLEFT = goog.getMsg('items left');
    case goog.i18n.pluralRules.Keyword.ONE:
      
/**
        @desc One item left.
        @protected
      */
      return este.demos.app.todomvc.todos.list.View.MSG_ONE_ITEMLEFT = goog.getMsg('item left');
    case goog.i18n.pluralRules.Keyword.TWO:
      
/**
        @desc Two items left.
        @protected
      */
      return este.demos.app.todomvc.todos.list.View.MSG_TWO_ITEMLEFT = goog.getMsg('items left');
    case goog.i18n.pluralRules.Keyword.FEW:
      
/**
        @desc Few items left.
        @protected
      */
      return este.demos.app.todomvc.todos.list.View.MSG_FEW_ITEMLEFT = goog.getMsg('items left');
    case goog.i18n.pluralRules.Keyword.MANY:
      
/**
        @desc Many items left.
        @protected
      */
      return este.demos.app.todomvc.todos.list.View.MSG_MANY_ITEMLEFT = goog.getMsg('items left');
    default:
      
/**
        @desc Other items left.
        @protected
      */
      return este.demos.app.todomvc.todos.list.View.MSG_OTHER_ITEMLEFT = goog.getMsg('items left');
  }
};