// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.layout.bla.View.
*/
goog.provide('este.demos.app.layout.bla.View');
goog.require('este.app.View');
goog.require('este.demos.app.layout.bla.templates');

/**
  @constructor
  @extends {este.app.View}
*/
este.demos.app.layout.bla.View = function() {
  este.demos.app.layout.bla.View.superClass_.constructor.call(this);
}
goog.inherits(este.demos.app.layout.bla.View, este.app.View);

/**
  @override
*/
este.demos.app.layout.bla.View.prototype.enterDocument = function() {
  este.demos.app.layout.bla.View.superClass_.enterDocument.call(this);
  this.on('div', 'click', this.onDivClick);
};

/**
  @param {goog.events.BrowserEvent} e
  @protected
*/
este.demos.app.layout.bla.View.prototype.onDivClick = function(e) {
  return alert('.este-content clicked');
};

/**
  @override
*/
este.demos.app.layout.bla.View.prototype.update = function() {
  this.getElement().innerHTML = este.demos.app.layout.bla.templates.element();
};