// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.layout.about.Presenter.
*/
goog.provide('este.demos.app.layout.about.Presenter');
goog.require('este.app.Presenter');
goog.require('este.demos.app.layout.about.View');
goog.require('este.demos.app.layout.layouts.master.View');

/**
  @constructor
  @extends {este.app.Presenter}
*/
este.demos.app.layout.about.Presenter = function() {
  este.demos.app.layout.about.Presenter.superClass_.constructor.call(this);
  this.view = new este.demos.app.layout.layouts.master.View({
    content: new este.demos.app.layout.about.View
  });
}
goog.inherits(este.demos.app.layout.about.Presenter, este.app.Presenter);