// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Router factory.
  @see /demos/router/routerhash.html
  @see /demos/router/routerhashtouch.html
  @see /demos/router/routerhtml5.html
*/
goog.provide('este.router.create');
goog.require('este.events.GestureHandler');
goog.require('este.History');
goog.require('este.Router');

/**
  @param {Element=} element
  @param {boolean=} forceHash
  @param {string=} pathPrefix Should start and end with slash.
  @return {este.Router}
*/
este.router.create = function(element, forceHash, pathPrefix) {
  var gestureHandler, history;
  if (element == null) {
    element = document.body;
  }
  history = new este.History(forceHash, pathPrefix);
  gestureHandler = new este.events.GestureHandler(element);
  return new este.Router(history, gestureHandler);
};