// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.layout.layouts.master.View.
*/
goog.provide('este.demos.app.layout.layouts.master.View');
goog.require('este.app.View');
goog.require('este.demos.app.layout.layouts.master.templates');

/**
  @param {Object.<string, este.app.View>} views
  @constructor
  @extends {este.app.View}
*/
este.demos.app.layout.layouts.master.View = function(views) {
  this.content = views.content;
  this.addChild(this.content);
  este.demos.app.layout.layouts.master.View.superClass_.constructor.call(this);
}
goog.inherits(este.demos.app.layout.layouts.master.View, este.app.View);

/**
  @type {este.app.View}
  @protected
*/
este.demos.app.layout.layouts.master.View.prototype.content = null;

/**
  @override
*/
este.demos.app.layout.layouts.master.View.prototype.createDom = function() {
  este.demos.app.layout.layouts.master.View.superClass_.createDom.call(this);
  this.getElement().innerHTML = este.demos.app.layout.layouts.master.templates.element();
  this.renderLinks(this.getElementByClass('este-links'));
  this.content.render(this.getElementByClass('este-content'));
  this.renderSidebar(this.getElementByClass('este-sidebar'));
};

/**
  @param {Element} el
  @protected
*/
este.demos.app.layout.layouts.master.View.prototype.renderLinks = function(el) {
  return el.innerHTML = este.app.renderLinks(this, [
    {
      title: 'Home',
      presenter: este.demos.app.layout.home.Presenter,
      selected: this.content instanceof este.demos.app.layout.home.View || this.content instanceof este.demos.app.layout.bla.View || this.content instanceof este.demos.app.layout.foo.View
    }, {
      title: 'About',
      presenter: este.demos.app.layout.about.Presenter,
      selected: this.content instanceof este.demos.app.layout.about.View
    }, {
      title: 'Contacts',
      presenter: este.demos.app.layout.contacts.Presenter,
      selected: this.content instanceof este.demos.app.layout.contacts.View
    }
  ]);
};

/**
  @param {Element} el
  @protected
*/
este.demos.app.layout.layouts.master.View.prototype.renderSidebar = function(el) {
  return this.dom_.removeNode(el);
};