// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.app.screen.Base.
*/
goog.provide('este.app.screen.Base');
goog.require('este.ui.Component');

/**
  @constructor
  @extends {este.ui.Component}
*/
este.app.screen.Base = function() {
  este.app.screen.Base.superClass_.constructor.call(this);
}
goog.inherits(este.app.screen.Base, este.ui.Component);

/**
  @type {este.app.View}
  @protected
*/
este.app.screen.Base.prototype.previousView = null;

/**
  @type {este.app.View}
  @protected
*/
este.app.screen.Base.prototype.currentView = null;

/**
  @param {este.app.View} view
  @param {boolean} isNavigation
*/
este.app.screen.Base.prototype.show = goog.abstractMethod;

/**
  @param {este.app.View} view
*/
este.app.screen.Base.prototype.hide = goog.abstractMethod;

/**
  @protected
*/
este.app.screen.Base.prototype.removePreviousView = function() {
  if (!this.previousView) {
    return;
  }
  return this.dom_.removeNode(this.previousView.getElement());
};

/**
  @param {este.app.View} view
  @protected
*/
este.app.screen.Base.prototype.setCurrentView = function(view) {
  this.currentView = view;
  return this.getElement().setAttribute('e-app-screen-active-view', this.currentView.className);
};

/**
  @protected
*/
este.app.screen.Base.prototype.lazyRenderView = function() {
  if (this.currentView.getElement()) {
    this.getElement().appendChild(this.currentView.getElement());
    this.currentView.enterDocument();
  } else {
    this.currentView.render(this.getElement());
  }
};

/**
  @protected
*/
este.app.screen.Base.prototype.rememberPreviousView = function() {
  return this.previousView = this.currentView;
};

/**
  Iphone needs explicit window.scrollTo 0, 0 to reset actual scroll. Ipad
  is ok. Both iphone and ipad needs setTimeout 0 for window.scrollTo, to
  prevent ugly scroll jumps and fixed positioned elements flickering.
  @param {number} x
  @param {number} y
  @protected
*/
este.app.screen.Base.prototype.scrollTo = function(x, y) {
  var _this = this;
  return setTimeout(function() {
    return window.scrollTo(0, 0);
  }, 0);
};