// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.app.screen.Base', function() {
  var Base, base;
  Base = este.app.screen.Base;
  base = null;
  setup(function() {
    return base = new Base;
  });
  suite('constructor', function() {
    return test('should work', function() {
      return assert.instanceOf(base, Base);
    });
  });
  suite('show', function() {
    return test('should throw exception', function(done) {
      var e;
      try {
        return base.show();
      } catch (_error) {
        e = _error;
        return done();
      }
    });
  });
  return suite('hide', function() {
    return test('should throw exception', function(done) {
      var e;
      try {
        return base.hide();
      } catch (_error) {
        e = _error;
        return done();
      }
    });
  });
});