// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Factory to create screen for concrete device.
*/
goog.provide('este.app.screen.create');
goog.require('este.app.screen.OneView');

/**
  @param {boolean} scrollingOnHistory
  @return {este.app.screen.Base}
*/
este.app.screen.create = function(scrollingOnHistory) {
  return new este.app.screen.OneView(scrollingOnHistory);
};