// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.app.screen.OneView', function() {
  var OneView, oneView, oneViewEl;
  OneView = este.app.screen.OneView;
  oneView = null;
  oneViewEl = null;
  setup(function() {
    oneView = new OneView;
    oneViewEl = document.createElement('div');
    return oneView.decorate(oneViewEl);
  });
  return suite('constructor', function() {
    return test('should work', function() {
      return assert.instanceOf(oneView, OneView);
    });
  });
});