// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Simple view manager. It switches view elements without fancy
  animation. Use it for desktop or old mobile devices, where FX is slow and
  ```-webkit-overflow-scrolling: touch;``` does not work.
*/
goog.provide('este.app.screen.OneView');
goog.require('este.app.screen.Base');
goog.require('goog.dom');
goog.require('goog.dom.classlist');
goog.require('goog.userAgent');

/**
  @param {boolean} scrollingOnHistory
  @constructor
  @extends {este.app.screen.Base}
*/
este.app.screen.OneView = function(scrollingOnHistory) {
  this.scrollingOnHistory = scrollingOnHistory;
  este.app.screen.OneView.superClass_.constructor.call(this);
  goog.dom.classlist.add(document.documentElement, 'e-app-screen-oneview');
}
goog.inherits(este.app.screen.OneView, este.app.screen.Base);

/**
  @type {boolean}
  @protected
*/
este.app.screen.OneView.prototype.scrollingOnHistory = true;

/**
  @override
*/
este.app.screen.OneView.prototype.enterDocument = function() {
  este.app.screen.OneView.superClass_.enterDocument.call(this);
  if (this.scrollingOnHistory) {
    this.on(window, 'scroll', this.onWindowScroll);
  }
};

/**
  @param {goog.events.BrowserEvent} e
  @protected
*/
este.app.screen.OneView.prototype.onWindowScroll = function(e) {
  if (!this.currentView) {
    return;
  }
  return this.currentView.scroll = goog.dom.getDocumentScroll();
};

/**
  @param {boolean} isNavigation
  @protected
*/
este.app.screen.OneView.prototype.updateScroll = function(isNavigation) {
  var update,
    _this = this;
  update = function() {
    if (isNavigation && _this.currentView.scroll) {
      return window.scrollTo(_this.currentView.scroll.x, _this.currentView.scroll.y);
    } else {
      return _this.scrollTo(0, 0);
    }
  };
  if (goog.userAgent.MOBILE) {
    return setTimeout(update, 0);
  } else {
    return update();
  }
};

/**
  @override
*/
este.app.screen.OneView.prototype.show = function(view, isNavigation) {
  this.removePreviousView();
  this.setCurrentView(view);
  this.lazyRenderView();
  this.rememberPreviousView();
  return this.updateScroll(isNavigation);
};

/**
  @override
*/
este.app.screen.OneView.prototype.hide = function(view) {
  return view.exitDocument();
};