// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Watch clicking on anchors elements. It uses Polymer
  PointerEvents to enable fast click on touch devices.
  Note, this trick does not work on iOS also sometimes we need zoom.
  https://plus.google.com/u/0/+RickByers/posts/ej7nsuoaaDa
  @see TODO
*/
goog.provide('este.labs.events.AnchorClickHandler');
goog.require('este.Base');
goog.require('este.thirdParty.pointerEvents');

/**
  @param {Element=} element
  @constructor
  @extends {este.Base}
*/
este.labs.events.AnchorClickHandler = function(element) {
  this.element = element != null ? element : document.documentElement;
  este.labs.events.AnchorClickHandler.superClass_.constructor.call(this);
  este.thirdParty.pointerEvents.install();
  this.registerEvents();
}
goog.inherits(este.labs.events.AnchorClickHandler, este.Base);

/**
  @type {Element}
  @protected
*/
este.labs.events.AnchorClickHandler.prototype.element = null;

/**
  @protected
*/
este.labs.events.AnchorClickHandler.prototype.registerEvents = function() {
  this.on(this.element, goog.events.EventType.CLICK, this.onElementClick);
  if (!este.thirdParty.pointerEvents.isSupported()) {
    return;
  }
  return this.on(this.element, goog.events.EventType.POINTERUP, this.onElementPointerUp);
};

/**
  @param {goog.events.BrowserEvent} e
  @protected
*/
este.labs.events.AnchorClickHandler.prototype.onElementClick = function(e) {
  var anchor;
  anchor = this.tryGetClickableAnchor(e.target);
  if (!anchor) {
    return;
  }
  e.preventDefault();
  if (este.thirdParty.pointerEvents.isSupported()) {
    return;
  }
  return this.dispatchClick(anchor);
};

/**
  @param {goog.events.BrowserEvent} e
  @protected
*/
este.labs.events.AnchorClickHandler.prototype.onElementPointerUp = function(e) {
  var anchor;
  anchor = this.tryGetClickableAnchor(e.target);
  if (!anchor) {
    return;
  }
  return this.dispatchClick(anchor);
};

/**
  @param {Node} node
  @return {Element}
  @protected
*/
este.labs.events.AnchorClickHandler.prototype.tryGetClickableAnchor = function(node) {
  return goog.dom.getAncestorByTagNameAndClass(node, goog.dom.TagName.A);
};

/**
  @param {Element} anchor
  @protected
*/
este.labs.events.AnchorClickHandler.prototype.dispatchClick = function(anchor) {
  return this.dispatchEvent({
    type: goog.events.EventType.CLICK,
    target: anchor
  });
};