// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.app.layout.foo.View.
*/
goog.provide('este.demos.app.layout.foo.View');
goog.require('este.app.View');
goog.require('este.demos.app.layout.foo.templates');
goog.require('este.ui.Resizer');
goog.require('goog.dom.classlist');

/**
  @constructor
  @extends {este.app.View}
*/
este.demos.app.layout.foo.View = function() {
  este.demos.app.layout.foo.View.superClass_.constructor.call(this);
}
goog.inherits(este.demos.app.layout.foo.View, este.app.View);

/**
  @type {este.ui.Resizer}
  @protected
*/
este.demos.app.layout.foo.View.prototype.resizer = null;

/**
  @override
*/
este.demos.app.layout.foo.View.prototype.enterDocument = function() {
  este.demos.app.layout.foo.View.superClass_.enterDocument.call(this);
  this.update();
  this.createResizer();
};

/**
  @override
*/
este.demos.app.layout.foo.View.prototype.exitDocument = function() {
  este.demos.app.layout.foo.View.superClass_.exitDocument.call(this);
  this.resizer.dispose();
};

/**
  @override
*/
este.demos.app.layout.foo.View.prototype.update = function() {
  this.getElement().innerHTML = este.demos.app.layout.foo.templates.element();
};

/**
  @protected
*/
este.demos.app.layout.foo.View.prototype.createResizer = function() {
  var _this = this;
  this.resizer = este.ui.Resizer.create();
  this.resizer.targetFilter = function(el) {
    return goog.dom.classlist.contains(el, 'este-box');
  };
  return this.resizer.decorate(this.getElement());
};