// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Factory for este.App.
  @namespace este.app
*/
goog.provide('este.app.create');
goog.require('este.App');
goog.require('este.app.screen.create');
goog.require('este.router.create');

/**
  @param {string|Element} element
  @param {{
    forceHash: (boolean|undefined),
    scrollingOnHistory: (boolean|undefined)
  }=} opt_options
  @return {este.App}
*/
este.app.create = function(element, opt_options) {
  var options, router, screen;
  options = {
    forceHash: true,
    scrollingOnHistory: true
  };
  if (opt_options) {
    goog.mixin(options, opt_options);
  }
  element = goog.dom.getElement(element);
  router = este.router.create(element, options.forceHash);
  screen = este.app.screen.create(options.scrollingOnHistory);
  screen.decorate(element);
  return new este.App(router, screen);
};