// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview Event class for este.App.

  Este App event types:

  - este.App.EventType.LOAD
  - este.App.EventType.SHOW
  - este.App.EventType.HIDE
  - este.App.EventType.TIMEOUT
  - este.App.EventType.ERROR
*/
goog.provide('este.app.Event');
goog.require('goog.events.Event');

/**
  @param {este.App.EventType} type
  @param {este.app.Request} request
  @param {*=} error
  @constructor
  @extends {goog.events.Event}
*/
este.app.Event = function(type, request, error) {
  this.request = request;
  this.error = error;
  este.app.Event.superClass_.constructor.call(this, type);
}
goog.inherits(este.app.Event, goog.events.Event);

/**
  @type {este.app.Request}
*/
este.app.Event.prototype.request = null;

/**
  @type {*}
*/
este.app.Event.prototype.error = null;