// Generated by github.com/steida/coffee2closure 0.0.14
suite('este.app.Event', function() {
  var Event, event;
  Event = este.app.Event;
  event = null;
  setup(function() {
    return event = new Event;
  });
  return suite('constructor', function() {
    test('should work', function() {
      return assert.instanceOf(event, Event);
    });
    return test('should set type and request', function() {
      var request;
      request = {};
      event = new Event('foo', request);
      assert.equal(event.type, 'foo');
      return assert.equal(event.request, request);
    });
  });
});