// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.react.TodoList.
*/
goog.provide('este.demos.react.todoList');
goog.require('este.react');
este.demos.react.todoList = este.react.create(/** @lends {React.ReactComponent.prototype} */({
  render: function() {
    var _this = this;
    return this.ul(this.props['items'].map(function(text) {
      return _this.li({
        'contentEditable': true
      }, text);
    }));
  }
}));