// Generated by github.com/steida/coffee2closure 0.0.14
/**
  @fileoverview este.demos.react.TodoApp.
*/
goog.provide('este.demos.react.todoApp');
goog.require('este.demos.react.todoList');
goog.require('este.react');
este.demos.react.todoApp = este.react.create(/** @lends {React.ReactComponent.prototype} */({
  getDefaultProps: function() {
    return {
      'items': []
    };
  },
  render: function() {
    return this.div([
      este.demos.react.todoList({
        'items': this.props['items']
      }), this.createSubmitForm()
    ]);
  },
  createSubmitForm: function() {
    return this.form({
      'onSubmit': this.onFormSubmit
    }, [
      this.input({
        'autoFocus': true,
        'ref': 'textInput'
      }), this.button("Add #" + (this.props['items'].length + 1))
    ]);
  },
  onFormSubmit: function(e) {
    var textInput;
    e.preventDefault();
    textInput = this.refs['textInput'].getDOMNode();
    this.setProps({
      'items': this.props['items'].concat(textInput.value.trim())
    });
    textInput.value = '';
    return textInput.focus();
  }
}));